export const data = {
  edges: [
    [0, 7],
    [1, 6],
    [2, 10],
    [3, 15],
    [4, 13],
    [5, 11],
    [6, 16],
    [7, 12],
    [8, 14],
    [9, 23],
    [10, 18],
    [11, 17],
    [12, 19],
    [13, 20],
    [14, 22],
    [15, 21],
    [16, 19],
    [17, 19],
    [18, 19],
    [20, 19],
    [21, 19],
    [22, 19],
    [23, 24],
    [24, 19],
  ],
  nodes: [
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 1 },
        src0: { kind: "none", value: 0 },
        src1: { kind: "none", value: 0 },
        literal: 32,
      },
      thread: 0,
      cluster: 0,
      SM: 1,
      pc: 0,
      last_pc: 0,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 1 },
        src0: { kind: "none", value: 0 },
        src1: { kind: "none", value: 0 },
        literal: 32,
      },
      thread: 0,
      cluster: 0,
      SM: 5,
      pc: 0,
      last_pc: 0,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 1 },
        src0: { kind: "none", value: 0 },
        src1: { kind: "none", value: 0 },
        literal: 32,
      },
      thread: 0,
      cluster: 0,
      SM: 6,
      pc: 0,
      last_pc: 0,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 1 },
        src0: { kind: "none", value: 0 },
        src1: { kind: "none", value: 0 },
        literal: 32,
      },
      thread: 0,
      cluster: 0,
      SM: 3,
      pc: 0,
      last_pc: 0,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 1 },
        src0: { kind: "none", value: 0 },
        src1: { kind: "none", value: 0 },
        literal: 32,
      },
      thread: 0,
      cluster: 0,
      SM: 4,
      pc: 0,
      last_pc: 0,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 1 },
        src0: { kind: "none", value: 0 },
        src1: { kind: "none", value: 0 },
        literal: 32,
      },
      thread: 0,
      cluster: 0,
      SM: 2,
      pc: 0,
      last_pc: 0,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 2 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 5,
      pc: 1,
      last_pc: 1,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 2 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 1,
      pc: 1,
      last_pc: 1,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 1 },
        src0: { kind: "none", value: 0 },
        src1: { kind: "none", value: 0 },
        literal: 32,
      },
      thread: 0,
      cluster: 0,
      SM: 0,
      pc: 0,
      last_pc: 0,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 1 },
        src0: { kind: "none", value: 0 },
        src1: { kind: "none", value: 0 },
        literal: 32,
      },
      thread: 0,
      cluster: 0,
      SM: 7,
      pc: 0,
      last_pc: 0,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 2 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 6,
      pc: 1,
      last_pc: 1,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 2 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 2,
      pc: 1,
      last_pc: 1,
    },
    {
      instruction: {
        format: "ALU",
        op: "div",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 3 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "reg", value: 2 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 1,
      pc: 2,
      last_pc: 2,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 2 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 4,
      pc: 1,
      last_pc: 1,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 2 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 0,
      pc: 1,
      last_pc: 1,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 2 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 3,
      pc: 1,
      last_pc: 1,
    },
    {
      instruction: {
        format: "ALU",
        op: "div",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 3 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "reg", value: 2 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 5,
      pc: 2,
      last_pc: 2,
    },
    {
      instruction: {
        format: "ALU",
        op: "div",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 3 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "reg", value: 2 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 2,
      pc: 2,
      last_pc: 2,
    },
    {
      instruction: {
        format: "ALU",
        op: "div",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 3 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "reg", value: 2 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 6,
      pc: 2,
      last_pc: 2,
    },
    {
      instruction: {
        format: "MEM",
        op: "st",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "mem", value: 2 },
        src0: { kind: "reg", value: 3 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 1,
      pc: 3,
      last_pc: 3,
    },
    {
      instruction: {
        format: "ALU",
        op: "div",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 3 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "reg", value: 2 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 4,
      pc: 2,
      last_pc: 2,
    },
    {
      instruction: {
        format: "ALU",
        op: "div",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 3 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "reg", value: 2 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 3,
      pc: 2,
      last_pc: 2,
    },
    {
      instruction: {
        format: "ALU",
        op: "div",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 3 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "reg", value: 2 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 0,
      pc: 2,
      last_pc: 2,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 2 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 7,
      pc: 1,
      last_pc: 1,
    },
    {
      instruction: {
        format: "ALU",
        op: "div",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 3 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "reg", value: 2 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 7,
      pc: 2,
      last_pc: 2,
    },
  ],
};
